# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-10-07 13:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='status',
            field=models.NullBooleanField(),
        ),
    ]
